version: '3'
services:
  apps:
    build:
      context: apps
      args:
        START_ENV: development
    container_name: collabospace_app 
    tty: true
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Tokyo"
      APP_DATABASE_HOST: collabospace_db
      APP_DATABASE: collabospace
      APP_DATABASE_USER: root
      APP_DATABASE_PASSWORD: collabospace 
      APP_SERVER_ENV: development
      APP_SERVER_ENV_SMTP_HOSTNAME: collabospace_smtp
      APP_SERVER_ENV_SMTP_PORT: 1025
      RAILS_ENV: development
    depends_on:
      - db
    volumes:
      - ./apps/app:/usr/src/app
    restart: unless-stopped
    networks:
      - collabospace_net

  db:
    build: db
    container_name: collabospace_db
    ports:
      - 33306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: collabospace 
    restart: unless-stopped
    networks:
      - collabospace_net
  smtp:
    image: sj26/mailcatcher
    container_name: collabospace_smtp
    ports:
      - 3080:1080
      - 3025:1025
    environment:
      TZ: "Asia/Tokyo"
    restart: unless-stopped
    networks:
      - collabospace_net
volumes:
  mysql-data:
    driver: local
  bundle:

networks:
  collabospace_net:
    driver: bridge
